TWITTER_ACCOUNTS = {
    'R. Bardet': '@romainbardet',
    'W. Barguil': '@WarrenBarguil',
    'J. Castroviejo Nicolas:': '@jcastroviejo',
    'A. Contador': '@albertocontador',
    'T. Gallopin': '@tonygallopin',
    'S. Geschke': '@simongeschke',
    'R. Gesink': '@RGUpdate',
    'J. Herrada Lopez': '@joherradalopez',
    'S. Kruijswijk': '@s_kruijswijk',
    'B. Mollema': '@BaukeMollema',
    'S. Pauwels': '@sergepauwels',
    'T. Pinot': '@ThibautPinot',
    'M. Rogers': '@mickrogers',
    'P. Sagan': '@petosagan',
    'A. Talansky': '@andrewtalansky',
    'D. Teklehaimanot': '@DanielTeklehai1',
    'R. Uran Uran': '@UranRigoberto',
    'A. Valverde Belmonte': '@alejanvalverde',
    'B. Vaugrenard': '@benvaugrenard',
    'T. Wellens': '@Tim_Wellens',
    'T. Voeckler': '@voecklerthomas',
    'A. Yates': '@AdamYates7',
}
